from playwright.sync_api import sync_playwright
from pathlib import Path
import subprocess,sys,time,os,json
root=Path(__file__).resolve().parents[1];out=root/'Documentation/evidence';out.mkdir(exist_ok=True)
video=root/'Video';env=os.environ.copy();env.update({'HLD_MODE':'local','HF_HUB_OFFLINE':'1','HF_HUB_DISABLE_TELEMETRY':'1'})
server=subprocess.Popen([sys.executable,'-m','streamlit','run',str(root/'Code/app.py'),'--server.port=8522','--server.address=127.0.0.1','--browser.gatherUsageStats=false'],env=env,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
time.sleep(3)
try:
 with sync_playwright() as p:
  browser=p.chromium.launch(headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
  context=browser.new_context(viewport={'width':1440,'height':1000},record_video_dir=str(video/'capture'),record_video_size={'width':1440,'height':1000})
  page=context.new_page();page.goto('http://127.0.0.1:8522');page.get_by_role('button',name='Retrieve and answer',exact=True).wait_for(timeout=180000)
  started=time.monotonic()
  def scene(caption,seconds=25):
   page.evaluate('''(text)=>{let e=document.getElementById('demo-caption');if(!e){e=document.createElement('div');e.id='demo-caption';e.style='position:fixed;bottom:0;left:0;right:0;z-index:999999;background:#16345c;color:white;padding:18px 30px;font:20px/1.45 Arial;border-top:4px solid #24c2b2';document.body.appendChild(e)}e.textContent=text}''',caption)
   print(caption,flush=True);time.sleep(seconds)
  def question(text):
   page.get_by_role('tab',name='Cited Q&A',exact=True).click();page.get_by_label('Engineering question').fill(text);page.get_by_role('button',name='Retrieve and answer',exact=True).click();time.sleep(12)
  scene('CS1 AUTOSAR HLD Intelligence Assistant | Student, Institution, PRN STUDENT_PRN. Automated recording of the working app; captions generated with AI assistance.',25)
  page.get_by_role('tab',name='Knowledge base',exact=True).click();page.get_by_text('Powertrain HLD · 2.0 · powertrain',exact=True).click()
  scene('INPUT DATA: five original synthetic JSON documents, 25 sections, two powertrain revisions. No proprietary OEM documents or licensed standards text are indexed.',25)
  page.screenshot(path=str(out/'06_knowledge_base_local.png'),full_page=True)
  page.get_by_role('tab',name='Cited Q&A',exact=True).click()
  scene('PIPELINE: section chunks → local BGE embeddings via PyTorch → FAISS similarity search → project/version filtering → Qwen GGUF → JSON and citation checks → human review.',25)
  question('What is the PedalPosition timeout in the current revision?')
  scene('CURRENT REVISION QUESTION: inspect the model answer and its source IDs. The synthetic v2.0 timeout is 50 ms. Citations identify document, revision and section.',25)
  page.screenshot(path=str(out/'07_cited_answer_local.png'),full_page=True)
  page.get_by_role('tab',name='Cited Q&A',exact=True).click()
  for exp in page.locator('[data-testid="stExpander"]:visible').all():
   try:exp.locator('summary').click()
   except Exception:pass
  scene('GROUNDING: expand retrieval evidence and read the exact source text. Similarity is not a correctness probability, and a valid citation ID is not proof of entailment.',25)
  page.get_by_role('tab',name='Architecture inventory',exact=True).click()
  scene('STRUCTURED EXTRACTION: deterministic parsing produces components, signals, interfaces and dependencies with section citations. Exportable JSON preserves traceability.',25)
  page.get_by_role('tab',name='Revision comparison',exact=True).click();page.get_by_text('TIMEOUT · modified',exact=True).click()
  scene('REVISION COMPARISON: v1.0 has 100 ms; v2.0 has 50 ms. Changed sections carry citations to both revisions. Source documents are not automatically modified.',25)
  page.screenshot(path=str(out/'08_revision_comparison_local.png'),full_page=True)
  page.get_by_role('tab',name='Cited Q&A',exact=True).click()
  combos=page.get_by_role('combobox');combos.nth(2).click();page.get_by_role('option',name='1.0',exact=True).click();time.sleep(2)
  question('What was the PedalPosition timeout in revision 1.0?')
  scene('HISTORICAL SEARCH: selecting revision 1.0 retrieves historical evidence rather than silently mixing old and current sources. The recorded answer must still be reviewed.',25)
  combos=page.get_by_role('combobox');combos.nth(1).click();page.get_by_role('option',name='thermal',exact=True).click();time.sleep(2)
  page.get_by_role('tab',name='Architecture inventory',exact=True).click()
  scene('CANDIDATE FINDINGS: thermal data deliberately contain IFan percent/rpm mismatch and an undeclared MissingSensor dependency. These are seeded fixtures, not field defects.',25)
  page.screenshot(path=str(out/'09_thermal_findings_local.png'),full_page=True)
  combos=page.get_by_role('combobox');combos.nth(1).click();page.get_by_role('option',name='powertrain',exact=True).click();time.sleep(2)
  question('What is the weather in Mumbai tomorrow?')
  scene('LIMITED SCOPE: an unsupported weather question is refused. Missing specification fields are also refused. These guards reduce risk but do not make the small model universally reliable.',25)
  page.get_by_role('tab',name='Review queue',exact=True).click();page.get_by_label('Reviewer name').fill('AUTOMATED_DEMO_REVIEWER');page.get_by_label('Evidence-based review note').fill('Demo record only. Submission reviewed by student on 07/10/2026. Engineering approval of demo outputs remains pending.');page.get_by_role('button',name='Save review',exact=True).click()
  scene('HUMAN REVIEW WORKFLOW: the demo records NEEDS_CHANGES in SQLite. This automated example is not a student signature, faculty approval or production design approval.',25)
  page.screenshot(path=str(out/'10_review_queue_local.png'),full_page=True)
  page.get_by_role('tab',name='Evaluation',exact=True).click()
  scene('EVALUATION: inspect the saved fixed-set metrics and all failed cases. Baseline and local-model runs are separate. No real-vehicle accuracy or productivity claim is made.',25)
  page.screenshot(path=str(out/'11_evaluation_local.png'),full_page=True)
  elapsed=time.monotonic()-started
  scene('LIMITATIONS AND HANDOFF: synthetic corpus; small model; heuristic answer checks; no OCR, enterprise RBAC or compliance certification. Review code, results and disclosures before submitting.',max(10,365-elapsed))
  recording=page.video.path();context.close();browser.close()
  (video/'recording_metadata.json').write_text(json.dumps({'recorded_file':Path(recording).name,'duration_target_seconds':365,'recording':'Actual working local Streamlit app, automated Playwright interactions, no student narration','mode':'local','data':'synthetic'},indent=2))
  print('VIDEO_PATH',recording,flush=True)
finally:server.terminate()
